name: Tests

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - "**/*.cpp"
    - ".github/**/*.yml"
    - "Makefile"
    - "tests/**"
    - "lit.cfg.py"
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install lit
      run: pip install lit
    - name: Install FileCheck
      run: sudo apt install llvm-15-tools && sudo ln -s /usr/bin/FileCheck-15 /usr/bin/FileCheck && sudo ln -s /usr/lib/llvm-15/bin/not /usr/bin/not
    - name: Install aarch64-gnu-linux-gcc
      run: sudo apt install gcc-aarch64-linux-gnu
    - name: Install qemu
      run: sudo apt install qemu-user
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-15.0.6
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0.6"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Test Debug build (normal)
      run: make test
    - name: Remove previous build
      run: make clean
    - name: Test Production build
      run: make && lit -j1 -sv .

