name: Tests

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - "**/*.cpp"
    - ".github/**/*.yml"
    - "Makefile"
    - "tests/**"
    - "lit.cfg.py"
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install lit
        # filecheck
        sudo apt install llvm-15-tools && sudo ln -s /usr/bin/FileCheck-15 /usr/bin/FileCheck && sudo ln -s /usr/lib/llvm-15/bin/not /usr/bin/not
        # aarch64-gnu-linux-gcc, qemu-aarch64, ...
        sudo apt install gcc-aarch64-linux-gnu qemu-user libtinfo5 libncurses-dev cmake extra-cmake-modules terminfo gcc g++
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-16.0.0
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "16.0.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Test Debug build (normal)
      run: LLVM_BUILD_DIR=./llvm make -e test
    - name: Remove previous build
      run: make clean
    - name: Test Production build
      run: LLVM_BUILD_DIR=./llvm make -e && lit -j1 -sv .

